version: '3'

services:
  db:
    image: postgres
    restart: always
    networks:
      - backend
    volumes:
      - ./.db-data:/var/lib/postgresql/data
      - ./src/config/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    env_file:
      - ./src/config/.env

  src:
    build: src
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - db

volumes:
  db_data:

networks:
  backend:
    driver: bridge
